export const localUsers = [
  {
    firstName: 'Leticia',
    lastName: 'Linscott',
    email: 'llinscott1@gmail.com',
    password: 'VtBW9r43wf4e453L',
    age: 23,
    gender: 'F',
    address1: '35359 Forest Crossing',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F16.jpg',
    aboutMe:
      'I am a UX designer who loves to paint, take photos, and spend time with my family and friends on the weekends.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Emma',
    lastName: 'Padmore',
    email: 'epadmore2@gmail.com',
    password: 'SpXEMQm4533454rff4',
    age: 30,
    gender: 'F',
    address1: '928 Maryland Drive',
    address2: 'Suite 79',
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F5.jpg',
    aboutMe:
      'I am a teacher who loves to spend my free time reading, writing, and practicing mindfulness.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Oliver',
    lastName: 'Reddyhoff',
    email: 'dreddyhoff3@gmail.com',
    password: '3ukaWNfefer4534543j',
    age: 34,
    gender: 'M',
    address1: '60 Loftsgordon Terrace',
    address2: null,
    city: 'Bronx',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10451,
    avatarUrl: '/assets/demoUserImg/M2.jpg',
    aboutMe:
      'Hey, my name is Oliver and I am a web developer who loves to ride my bike, play guitar, and experiment with new recipes in the kitchen.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
];
