const ratingData = [
  {
    userId: 1,
    buddyId: 26,
    rating: 3,
    isReport: true,
    reportComment:
      'donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam',
    reportisUpheld: true,
    meetingId: 8,
  },
  {
    userId: 2,
    buddyId: 1,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 63,
  },
  {
    userId: 3,
    buddyId: 25,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 32,
  },
  {
    userId: 4,
    buddyId: 56,
    rating: 5,
    isReport: true,
    reportComment:
      'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in',
    reportisUpheld: false,
    meetingId: 93,
  },
  {
    userId: 5,
    buddyId: 39,
    rating: 5,
    isReport: true,
    reportComment:
      'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum',
    reportisUpheld: true,
    meetingId: 84,
  },
  {
    userId: 6,
    buddyId: 69,
    rating: 5,
    isReport: true,
    reportComment:
      'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci',
    reportisUpheld: false,
    meetingId: 82,
  },
  {
    userId: 7,
    buddyId: 40,
    rating: 3,
    isReport: true,
    reportComment:
      'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est',
    reportisUpheld: true,
    meetingId: 47,
  },
  {
    userId: 8,
    buddyId: 72,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 60,
  },
  {
    userId: 9,
    buddyId: 91,
    rating: 4,
    isReport: true,
    reportComment:
      'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi',
    reportisUpheld: false,
    meetingId: 50,
  },
  {
    userId: 10,
    buddyId: 88,
    rating: 5,
    isReport: true,
    reportComment:
      'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate',
    reportisUpheld: false,
    meetingId: 26,
  },
  {
    userId: 11,
    buddyId: 47,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 38,
  },
  {
    userId: 12,
    buddyId: 8,
    rating: 1,
    isReport: true,
    reportComment:
      'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices',
    reportisUpheld: false,
    meetingId: 71,
  },
  {
    userId: 13,
    buddyId: 88,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 4,
  },
  {
    userId: 14,
    buddyId: 69,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 90,
  },
  {
    userId: 15,
    buddyId: 48,
    rating: 5,
    isReport: true,
    reportComment:
      'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed',
    reportisUpheld: true,
    meetingId: 53,
  },
  {
    userId: 16,
    buddyId: 6,
    rating: 2,
    isReport: true,
    reportComment:
      'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse',
    reportisUpheld: false,
    meetingId: 73,
  },
  {
    userId: 17,
    buddyId: 73,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 93,
  },
  {
    userId: 18,
    buddyId: 54,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 100,
  },
  {
    userId: 19,
    buddyId: 51,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 5,
  },
  {
    userId: 20,
    buddyId: 55,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 41,
  },
  {
    userId: 21,
    buddyId: 98,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 95,
  },
  {
    userId: 22,
    buddyId: 16,
    rating: 4,
    isReport: true,
    reportComment:
      'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat',
    reportisUpheld: true,
    meetingId: 65,
  },
  {
    userId: 23,
    buddyId: 69,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 70,
  },
  {
    userId: 24,
    buddyId: 15,
    rating: 3,
    isReport: true,
    reportComment:
      'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus',
    reportisUpheld: true,
    meetingId: 52,
  },
  {
    userId: 25,
    buddyId: 36,
    rating: 2,
    isReport: true,
    reportComment:
      'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac',
    reportisUpheld: true,
    meetingId: 48,
  },
  {
    userId: 26,
    buddyId: 64,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 75,
  },
  {
    userId: 27,
    buddyId: 24,
    rating: 3,
    isReport: true,
    reportComment:
      'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce',
    reportisUpheld: true,
    meetingId: 35,
  },
  {
    userId: 28,
    buddyId: 1,
    rating: 5,
    isReport: true,
    reportComment:
      'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed',
    reportisUpheld: true,
    meetingId: 5,
  },
  {
    userId: 29,
    buddyId: 38,
    rating: 4,
    isReport: true,
    reportComment:
      'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl',
    reportisUpheld: false,
    meetingId: 32,
  },
  {
    userId: 30,
    buddyId: 37,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 71,
  },
  {
    userId: 31,
    buddyId: 27,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 54,
  },
  {
    userId: 32,
    buddyId: 81,
    rating: 2,
    isReport: true,
    reportComment:
      'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est',
    reportisUpheld: true,
    meetingId: 36,
  },
  {
    userId: 33,
    buddyId: 72,
    rating: 5,
    isReport: true,
    reportComment:
      'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien',
    reportisUpheld: false,
    meetingId: 69,
  },
  {
    userId: 34,
    buddyId: 61,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 37,
  },
  {
    userId: 35,
    buddyId: 94,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 17,
  },
  {
    userId: 36,
    buddyId: 27,
    rating: 4,
    isReport: true,
    reportComment:
      'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac',
    reportisUpheld: true,
    meetingId: 56,
  },
  {
    userId: 37,
    buddyId: 54,
    rating: 1,
    isReport: true,
    reportComment:
      'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis',
    reportisUpheld: true,
    meetingId: 15,
  },
  {
    userId: 38,
    buddyId: 52,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 10,
  },
  {
    userId: 39,
    buddyId: 18,
    rating: 3,
    isReport: true,
    reportComment:
      'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque',
    reportisUpheld: false,
    meetingId: 90,
  },
  {
    userId: 40,
    buddyId: 68,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 73,
  },
  {
    userId: 41,
    buddyId: 46,
    rating: 3,
    isReport: true,
    reportComment:
      'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede',
    reportisUpheld: true,
    meetingId: 69,
  },
  {
    userId: 42,
    buddyId: 16,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 45,
  },
  {
    userId: 43,
    buddyId: 19,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 87,
  },
  {
    userId: 44,
    buddyId: 13,
    rating: 2,
    isReport: true,
    reportComment:
      'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo',
    reportisUpheld: false,
    meetingId: 79,
  },
  {
    userId: 45,
    buddyId: 45,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 65,
  },
  {
    userId: 46,
    buddyId: 76,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 86,
  },
  {
    userId: 47,
    buddyId: 35,
    rating: 1,
    isReport: true,
    reportComment:
      'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio',
    reportisUpheld: false,
    meetingId: 12,
  },
  {
    userId: 48,
    buddyId: 42,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 19,
  },
  {
    userId: 49,
    buddyId: 97,
    rating: 5,
    isReport: true,
    reportComment:
      'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet',
    reportisUpheld: false,
    meetingId: 28,
  },
  {
    userId: 50,
    buddyId: 99,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 75,
  },
  {
    userId: 51,
    buddyId: 16,
    rating: 3,
    isReport: true,
    reportComment:
      'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis',
    reportisUpheld: true,
    meetingId: 18,
  },
  {
    userId: 52,
    buddyId: 8,
    rating: 5,
    isReport: true,
    reportComment:
      'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer',
    reportisUpheld: true,
    meetingId: 57,
  },
  {
    userId: 53,
    buddyId: 11,
    rating: 1,
    isReport: true,
    reportComment:
      'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam',
    reportisUpheld: true,
    meetingId: 83,
  },
  {
    userId: 54,
    buddyId: 42,
    rating: 5,
    isReport: true,
    reportComment:
      'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit',
    reportisUpheld: false,
    meetingId: 85,
  },
  {
    userId: 55,
    buddyId: 32,
    rating: 1,
    isReport: true,
    reportComment:
      'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non',
    reportisUpheld: false,
    meetingId: 88,
  },
  {
    userId: 56,
    buddyId: 51,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 84,
  },
  {
    userId: 57,
    buddyId: 21,
    rating: 2,
    isReport: true,
    reportComment:
      'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor',
    reportisUpheld: false,
    meetingId: 42,
  },
  {
    userId: 58,
    buddyId: 91,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 76,
  },
  {
    userId: 59,
    buddyId: 76,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 49,
  },
  {
    userId: 60,
    buddyId: 92,
    rating: 1,
    isReport: true,
    reportComment:
      'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed',
    reportisUpheld: false,
    meetingId: 51,
  },
  {
    userId: 61,
    buddyId: 70,
    rating: 2,
    isReport: true,
    reportComment:
      'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat',
    reportisUpheld: true,
    meetingId: 100,
  },
  {
    userId: 62,
    buddyId: 17,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 66,
  },
  {
    userId: 63,
    buddyId: 48,
    rating: 1,
    isReport: true,
    reportComment:
      'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a',
    reportisUpheld: false,
    meetingId: 89,
  },
  {
    userId: 64,
    buddyId: 57,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 19,
  },
  {
    userId: 65,
    buddyId: 12,
    rating: 4,
    isReport: true,
    reportComment:
      'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede',
    reportisUpheld: false,
    meetingId: 55,
  },
  {
    userId: 66,
    buddyId: 82,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 80,
  },
  {
    userId: 67,
    buddyId: 50,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 56,
  },
  {
    userId: 68,
    buddyId: 63,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 53,
  },
  {
    userId: 69,
    buddyId: 14,
    rating: 2,
    isReport: true,
    reportComment:
      'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus',
    reportisUpheld: true,
    meetingId: 35,
  },
  {
    userId: 70,
    buddyId: 52,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 99,
  },
  {
    userId: 71,
    buddyId: 82,
    rating: 3,
    isReport: true,
    reportComment:
      'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien',
    reportisUpheld: false,
    meetingId: 60,
  },
  {
    userId: 72,
    buddyId: 12,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 16,
  },
  {
    userId: 73,
    buddyId: 89,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 89,
  },
  {
    userId: 74,
    buddyId: 39,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 77,
  },
  {
    userId: 75,
    buddyId: 41,
    rating: 3,
    isReport: true,
    reportComment:
      'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum',
    reportisUpheld: false,
    meetingId: 17,
  },
  {
    userId: 76,
    buddyId: 42,
    rating: 5,
    isReport: true,
    reportComment:
      'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur',
    reportisUpheld: false,
    meetingId: 38,
  },
  {
    userId: 77,
    buddyId: 84,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 51,
  },
  {
    userId: 78,
    buddyId: 72,
    rating: 1,
    isReport: true,
    reportComment:
      'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at',
    reportisUpheld: true,
    meetingId: 84,
  },
  {
    userId: 79,
    buddyId: 11,
    rating: 4,
    isReport: true,
    reportComment:
      'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus',
    reportisUpheld: false,
    meetingId: 48,
  },
  {
    userId: 80,
    buddyId: 82,
    rating: 1,
    isReport: true,
    reportComment:
      'orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec',
    reportisUpheld: true,
    meetingId: 23,
  },
  {
    userId: 81,
    buddyId: 9,
    rating: 4,
    isReport: true,
    reportComment:
      'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in',
    reportisUpheld: false,
    meetingId: 57,
  },
  {
    userId: 82,
    buddyId: 33,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 22,
  },
  {
    userId: 83,
    buddyId: 72,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 89,
  },
  {
    userId: 84,
    buddyId: 93,
    rating: 1,
    isReport: true,
    reportComment:
      'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim',
    reportisUpheld: true,
    meetingId: 46,
  },
  {
    userId: 85,
    buddyId: 28,
    rating: 1,
    isReport: true,
    reportComment:
      'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id',
    reportisUpheld: false,
    meetingId: 18,
  },
  {
    userId: 86,
    buddyId: 46,
    rating: 3,
    isReport: true,
    reportComment:
      'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat',
    reportisUpheld: true,
    meetingId: 24,
  },
  {
    userId: 87,
    buddyId: 78,
    rating: 3,
    isReport: true,
    reportComment:
      'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien',
    reportisUpheld: false,
    meetingId: 33,
  },
  {
    userId: 88,
    buddyId: 74,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 93,
  },
  {
    userId: 89,
    buddyId: 77,
    rating: 4,
    isReport: true,
    reportComment:
      'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi',
    reportisUpheld: true,
    meetingId: 24,
  },
  {
    userId: 90,
    buddyId: 69,
    rating: 4,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 72,
  },
  {
    userId: 91,
    buddyId: 14,
    rating: 4,
    isReport: true,
    reportComment:
      'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer',
    reportisUpheld: true,
    meetingId: 92,
  },
  {
    userId: 92,
    buddyId: 86,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 60,
  },
  {
    userId: 93,
    buddyId: 79,
    rating: 5,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 55,
  },
  {
    userId: 94,
    buddyId: 60,
    rating: 3,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 92,
  },
  {
    userId: 95,
    buddyId: 44,
    rating: 2,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 4,
  },
  {
    userId: 96,
    buddyId: 29,
    rating: 3,
    isReport: true,
    reportComment:
      'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris',
    reportisUpheld: false,
    meetingId: 60,
  },
  {
    userId: 97,
    buddyId: 88,
    rating: 1,
    isReport: false,
    reportComment: null,
    reportisUpheld: false,
    meetingId: 55,
  },
  {
    userId: 98,
    buddyId: 7,
    rating: 2,
    isReport: true,
    reportComment:
      'eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes',
    reportisUpheld: true,
    meetingId: 83,
  },
  {
    userId: 99,
    buddyId: 71,
    rating: 1,
    isReport: true,
    reportComment:
      'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in',
    reportisUpheld: false,
    meetingId: 66,
  },
  {
    userId: 100,
    buddyId: 4,
    rating: 5,
    isReport: true,
    reportComment:
      'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut',
    reportisUpheld: false,
    meetingId: 10,
  },
];

module.exports = ratingData;
